# Generated by Django 5.0 on 2024-02-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='phno',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
